name: Build
on: [pull_request]

jobs:
    test:
        name: Perform build
        strategy:
            matrix:
                dc: [dmd, ldc]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build container
              run: |
                # build container
                docker build . -t d_c_arm_test
