name: Build
on: [push, pull_request]

jobs:
    setup:
        outputs:
            compilers: ${{ steps.load-config.outputs.compilers }}
    test:
        name: Perform build
        strategy:
            matrix:
                dc: [ldc]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build container
              run: |
                # build container
                docker build . -t d_c_arm_test
