name: Build
on: [pull_request]

jobs:
    test:
        name: Perform build
        strategy:
            matrix:
                dc: [ldc]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build container
              run: |
                # build container
                docker build . -t d_c_arm_test

            - name: Show compiled ELF file
              run: |
                docker run --rm -it d_c_arm_test:latest ls -alh /tmp/project/build/firmware\.elf
